### ISSUE TITLE
The link sections at the top need discrete, descriptive labelling

### ISSUE THREAD

**Issue by thorva** [chicken-mover/d3mok#11]
Just saying ON THIS PAGE: doesn't really explain why there are two different heaps, and doesn't give the reader any guidance on what to click on depending on what he's interested in. I propose--

ESSAYS:

SHORT PIECES:

**Comment by petronius** [comment]
I worry that "essays" pigeonholes the long pieces into being one kind of thing, and "short pieces" is sufficiently general language as to be bland.

But then I hate phrases like "long read" (which to my mind is 900 pages or more).

Maybe "Features"/"Shorts"? I dunno, I'm not happy with anything I can think of (which is one reason I just had it as "on this page" originally).

Or what about "Features"/"Also on this page" or something?

**Comment by petronius** [comment]
Fixed by 44b6cc1359d66bcf45de30a878cadddb481d9397 but I might revise the text at some point.
