### ISSUE TITLE
"Previously by this author" doesn't work

### ISSUE THREAD

**Issue by thorva** [chicken-mover/d3mok#5]
Seems to just identify the previous essay without regard to the author tag

**Comment by petronius** [comment]
Fixed by 21baf8cd21a80f734b717e2f0798aaaf4956fb35

**Comment by petronius** [comment]
Now the "Previously" text is displaying without a link if it is the first essay by that author.

**Comment by petronius** [comment]
Fixed by 44b6cc1359d66bcf45de30a878cadddb481d9397
