### ISSUE TITLE
Titles and subtitles not always parsed and escaped correctly

### ISSUE THREAD

**Issue by petronius** [chicken-mover/d3mok#6]

**Comment by petronius** [comment]
Fixed by 1f43965a46dccc276db7838cc72553235475f162 and eaf452d37d9ca7dfc59d7cf6fc366b6295c5d05f

**Comment by thorva** [comment]
Still not working properly on the Archive page.

**Comment by petronius** [comment]
Fixed by 44b6cc1359d66bcf45de30a878cadddb481d9397
