### ISSUE TITLE
Separation between tags

### ISSUE THREAD

**Issue by thorva** [chicken-mover/d3mok#9]
Tags need some kind of separation, even if it is just three spaces instead of one, because they can be multi-word themselves (cf. Musical Interlude test post)

**Comment by thorva** [comment]
Looking again at this, I think the solution may genuinely be commas: the whiteness will be a good divider, and the list in the entry field is comma-separated anyway so they're not a valid character in tags.

**Comment by petronius** [comment]
Fixed by 44b6cc1359d66bcf45de30a878cadddb481d9397 using blue semicolons, because I think semicolons are better phrase separators, and blue because white looked weird, but feel free to reopen if you hate it.
